voxpupuli/puppet-k8s

README.md, data/rspec.yaml, hiera-rspec.yaml, manifests/binary.pp, manifests/server/apiserver.pp, manifests/server/etcd.pp, manifests/server/tls.pp, spec/classes/k8s_spec.rb, spec/classes/server_spec.rb, spec/defines/binary_spec.rb
- prevent undef value if ipv6 is turned off
- fail if no etcd_servers are defined
- add proper links
i know, ci is failing, but want to know first if it would be okay like that?
if ipv6 is not available fact('networking.ip6') returns Undef and this breaks the typ TLS_Altnames.
does it make sense to run without etcd_servers nor discover_etcd_servers set to true?
atm i get 0 bytes files if i dont set it like this, how is this supposed to be? if one sets ensure to present but no source/content this will be an empty file. target alone does not make it a link.
=> prevent undef value if ipv6 is turned off, fail if not etcd_servers are defined

REFERENCE.md, manifests/init.pp, manifests/install/kubeadm.pp, manifests/install/kubectl.pp, manifests/node.pp, manifests/node/kubelet.pp, manifests/repo.pp, manifests/server.pp, manifests/server/apiserver.pp, manifests/server/etcd.pp, manifests/server/kubeadm.pp, manifests/server/tls/k8s_sign.pp, metadata.json, spec/classes/install/kubeadm_spec.rb, spec/classes/install/kubectl_spec.rb, spec/type_aliases/firewall.rb, types/firewall.pp
- include firewall class for dependency packages
- add ubuntu 22.04 and module dependencies to metadata
- move kubectl and kubeadm to generic install classes
- add firewall also for non firewalld systems
- add kubeadm tool to controller
- update class documentation
- add module dependency for augeasproviders_core
- add dependencies between sysctl and kmod
- require file kubectl before using it
- allow to set advertise_address
=> Patching v3

lib/puppet/provider/kubectl_apply/kubectl.rb, spec/unit/puppet/provider/kubectl_apply_resource/kubectl_spec.rb
The old `cascade=false` option is being fully removed from Kubernetes, and is in fact now deprecated on all supported versions. And even the most recent EoL versions understand `cascade=orphan`.
The recreate option might not be the most optimal design at the moment, but it should at least not error out if actually used.
=> Use cascade=orphan for kubectl_apply resources when told to recreate

manifests/server/resources/kube_proxy.pp, spec/fixtures/files/resources/kube-proxy-older.yaml, spec/fixtures/files/resources/kube-proxy.yaml
With dual-stack cluster CIDR this will generate a broken clusterCIDR parameter, as kube-proxy expects a comma-separated string.  
Additionally, when using the config file, any kubeconfig parameters specified in the launch options may be silently ignored.
=> Fix generated kube-proxy configmap

REFERENCE.md, manifests/init.pp, manifests/node.pp, manifests/server/resources.pp, spec/type_aliases/proxy_method_spec.rb, types/proxy_method.pp
Since this seems like it could be quite the footgun, it's probably best to use a type that makes it harder to deploy a broken cluster.  
It probably won't stop anyone determined enough, but it should at least make it easier to know what's going to happen based on the value assigned.
Fixes #28
=> Improve the kube-proxy management flag

manifests/server/etcd.pp, manifests/server/tls.pp
Just localhost and default routed IPs were added to a SAN before. That causes a problem on a server with multiple NICs when etcd or kube-apiserver should be accessed via non-default route.
=> Include every IP address into a cert's SAN field

manifests/server/etcd.pp, manifests/server/tls.pp, manifests/server/tls/ca.pp, manifests/server/tls/cert.pp, spec/defines/server/tls/ca_spec.rb, spec/defines/server/tls/cert_spec.rb
Some systems seem to be more particular about their path usage, and also sometimes realize the certification generation chain in slightly odd orders, so more control flow decisions - and the use of the path-fact - seems to be in order.
=> Some improvements to certificate generation

REFERENCE.md, manifests/server/etcd.pp, manifests/server/tls.pp
Reverts voxpupuli/puppet-k8s#32
To copy [what I said there](https://github.com/voxpupuli/puppet-k8s/pull/32#issuecomment-1506824282);
It's causing issues as it's changing the SAN list - and therefore also triggering a recreation of the serving certs - every time a container starts or stops on the Kubernetes master nodes.
Additionally, it's also including link-local bindings as well as IPVS entries from kube-proxy into the certificates, which causes the SAN list to grow in size far too quickly. A simple test cluster with no active load is already up to 50 SANs, while our production cluster would have SAN lists with almost a thousand entries for each master.
=> Revert "Include every IP address into a cert's SAN field"

manifests/server/tls/ca.pp, spec/defines/server/tls/ca_spec.rb
If there's no serial file on disk (no certificate has been signed by the CA), then openssl runs into issues trying to validate the CA against itself, which causes it to regenerate the CA even though it's still valid.
Fixes #37
=> Fix unintentional CA recreation if missing serial

REFERENCE.md, manifests/init.pp, manifests/server.pp, manifests/server/apiserver.pp, manifests/server/etcd.pp
- set etcd cluster name
- use etcd cluster name also in apiserver to collect only the matching etcd cluster
- add some docu strings
=> use etcd cluster name also in apiserver to collect only the matching etcd cluster

manifests/server/resources.pp, manifests/server/resources/kube_proxy.pp, spec/classes/server/resources/kube_proxy_spec.rb
- remove duplicated clusterRoleBinding from k8s::server::resource class
- add ServiceAccount to k8s::server::resource::kube_proxy class
- remove ServiceAccount from k8s::server::resource
- remove default value from specific resource declaration
=> remove duplicate CRB and move SA to kube-proxy class

REFERENCE.md, lib/puppet/provider/kubeconfig/ruby.rb, lib/puppet/type/kubeconfig.rb, spec/unit/puppet/provider/kubeconfig/kubectl_spec.rb, spec/unit/puppet/provider/kubeconfig/ruby_spec.rb, spec/unit/puppet/type/kubeconfig_spec.rb
Probably not the most optimal implementation, though it's best to at least ensure it's 0600 by default.
=> Handle file mode for kubeconfig files

REFERENCE.md, manifests/server/resources.pp, manifests/server/resources/coredns.pp, manifests/server/resources/flannel.pp, manifests/server/resources/kube_proxy.pp, spec/fixtures/files/resources/kube-proxy-older.yaml, spec/fixtures/files/resources/kube-proxy.yaml
Add imagePullSecrets to pull images from private registries. 
Does not manage the secret itself. only use existing secrets.
First setup control plane, maybe with errors because coredns/kube-proxy cannot be deployed. Then create the secret. Images should then be pulled automatically.
```yaml
---
k8s::server::resources::image_pull_secrets:
- name: my-private-registry-secret
```
=> add possibillity to use imagePullSecrets

REFERENCE.md, manifests/node.pp, manifests/node/kube_proxy.pp, manifests/node/kubelet.pp, spec/classes/node/kube_proxy_spec.rb
=> Expand use of Sensitive to match node tokens

REFERENCE.md, manifests/install/container_runtime.pp, spec/classes/install/container_runtime_spec.rb
Ran into the requirement to have a more specific CRI version in a few cases, so exposing the ensure parameter to make that particular setup easier to manage.
=> Expose ensure param for container runtime package

manifests/repo.pp, spec/classes/repo_spec.rb
Under https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/, the urls have moved from `CentOS_9` to `CentOS_9_Stream`. Eg: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_9_Stream/ and https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.26:/1.26.1/CentOS_9_Stream/.
When applying to a CentOS 9 machine.
=> Fix RedHat urls

manifests/node/kubelet.pp, manifests/server/apiserver.pp, manifests/server/etcd.pp, metadata.json
with puppetlabs/firewall 7.0.0 the parameter was renamed from **action** to **jump**
=> update firewall resources to use jump instead of action; require puppetlabs/firewall 7.x

REFERENCE.md, types/bootstrap_token.pp
The regex used to validate the bootstrap token allows strings that end with a newline. 
This PR makes the regex more strict by using `\z` instead of `$` to match the end of the string. (`\z` does not allow trailing newline characters).
When the bootstrap token contains a newline, worker nodes fail to join the cluster. The `kubelet` process  emit strange errors like:
```
kubelet[10895]: E0130 14:00:33.287321   10895 certificate_manager.go:562] kubernetes.io/kube-apiserver-client-kubelet: Failed while requesting a signed certificate from the control plane: cannot create certificate signing request: Post "https://kubernetes.vagrant.local:6443/apis/certificates.k8s.io/v1/certificatesigningrequests": net/http: invalid header field value for "Authorization"
kubelet[10895]: E0130 14:00:33.616337 …
```
=> Do not allow bootstrap tokens with a trailing newline

REFERENCE.md, types/bootstrap_token.pp
Follow up to https://github.com/voxpupuli/puppet-k8s/pull/79.
Fixes the same issue as https://github.com/voxpupuli/puppet-k8s/pull/79, but for the case when the bootstrap token starts with a newline character.
=> Do not allow bootstrap tokens with a leading newline

REFERENCE.md, manifests/install/cni_plugins.pp
This PR makes the download URL for the CNI plugins configurable by adding a new parameter to the `cni_plugins` class. The parameter is a template string, which is rendered using the `k8s::format_url` function. 
NOTE: The `k8s::format_url` function auto-detects the CPU architecture, so the `arch` parameter is no longer required. I am therefore removing it from the class. This could be a breaking change if users have set `arch` to something other than their system's actual CPU architecture. I don't think anyone is doing that though, since you would end up installing the k8s binaries for one architecture and the cni plugins for another.
The download URL is currently hard-coded to github.com. This makes it difficult to use the module in air-gapped environments.
=> Make cni_plugins download url configurable with a template string

REFERENCE.md, manifests/install/crictl.pp
This PR replaces the `download_url` parameter of the `crictl` class with a new parameter called `download_url_template`. This parameter uses template variables and is rendered using the `k8s::format_url` function, similar to how other download URLs are handled in this module. 
The k8s::format_url function auto-detects the CPU architecture, so the arch parameter is no longer required. I am therefore removing it from the class.
NOTE: This is a breaking change for users that use the `download_url` parameter. Should this be noted somewhere?
Without templating, it is cumbersome to override the download URL. The user has to handle the version and arch themselves. It is also inconsistent with other parts of the module that use templating for download URLs.
=> Use a template string for the crictl download URL

lib/puppet/type/kubectl_apply.rb
puppet generate types fails with
```
Failed to load custom type 'kubectl_apply' from '/etc/puppetlabs/code/environments/test/modules/k8s/lib/puppet/type/kubectl_apply.rb': uninitialized constant Puppet::Parameter::Boolean
```
Adding `require 'puppet/parameter/boolean'` to kubectl_apply type.
=> kubectl_apply: add missing require

REFERENCE.md, manifests/init.pp, spec/defines/binary_spec.rb
Updates the URL templates to use the new `dl.k8s.io` store instead of the older `storage.googleapis.com` one.
This also includes a bump to a non-EoL version of Kubernetes, one where the binaries are guaranteed to exist.
Fixes #100
=> Update binary repos and versions to support modern Kubernetes

REFERENCE.md, manifests/install/cni_plugins.pp, manifests/install/container_runtime.pp, manifests/repo.pp
Replaces the old kubic repositories with the isv:kubernetes `pkg.k8s.io` repositories instead, to keep support for non-EoL Kubernetes.
Also includes the necessary mid-step to support migrating a Debian install over to the new packages, as there are some differences in them.
Supersedes #94
Fixes #77 
Might improve #47 according to superseded PR - but not personally tested
=> Use pkgs.k8s.io repos instead of kubic

manifests/install/cni_plugins.pp, manifests/install/crictl.pp, manifests/server/etcd/setup.pp, spec/classes/server/etcd/setup_spec.rb
Makes the installation of cni_plugins, crictl & etcd similar to the way the main k8s binaries are installed. The archives are unpacked to folders in /opt and symlinked to /usr/local/bin . The target folder is unique per version, making it possible to update these components.
Fixes #95.
=> Unpack cni_plugins, crictl & etcd to folders in /opt and use symlinks

REFERENCE.md, manifests/server/apiserver.pp, manifests/server/etcd.pp
Actually missed the (really quite common) use-case of not having any cluster separation for ETCD on #66, so a quick fix to handle that correctly.
=> Correctly handle default name/discovery tag for etcd

manifests/common.pp, manifests/install/cni_plugins.pp, spec/classes/install/cni_plugins_spec.rb
Keeps custom CNI binaries around between upgrades of the main CNI plugins, to remove the need to redeploy any custom binaries that have been installed during the lifetime of the node/cluster.
Fixes #107
=> Retain custom CNI plugins over upgrades

manifests/server/etcd/setup.pp
Ensure that the etcd parameter specifying the list of etcd servers in a cluster is unique. This helps when `k8s::server::etcd::setup::initial_cluster` is not empty - allows to set the value globally for the whole cluster, not for each node separately without itself.
=> Make etcd initial_cluster unique list

REFERENCE.md, manifests/server/wait_online.pp
Default execution timeout is 300 seconds, with 15 retries it could stall puppet for 45 minutes if api server is not running.
=> Support configuration of waiting times

REFERENCE.md, manifests/binary.pp, manifests/common.pp, manifests/install/container_runtime.pp, manifests/node.pp, manifests/node/kubelet.pp
Will no longer break catalog compilation and/or application when turning off `manage_*` parameters, and also respects them more
=> Improve handling of manage_* parameters

manifests/server/resources/flannel.pp
Installation with flannel enabled (all default settings) has been broken since #116 
It will fail to start the CNI with this message:
```
Failed to create SubnetManager: error retrieving pod spec for 'kube-system/flannel-*****': pods "flannel-*****" is forbidden: User "system:serviceaccount:kube-system:flannel" cannot get resource "pods" in API group "" in the namespace "kube-system"
```
Allows `get` operation removed in #116 which flannel requires to start
=> Breakfix: flannel forbidden to query pod

manifests/server/etcd.pp
Add `clientAuth` to the list of etcd extended key usages
```
Jun 16 09:22:28 example etcd[10992]: {"level":"warn","ts":"2025-06-16T09:22:28.579816Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"[::1]:35480","server-name":"","error":"tls: failed to verify certificate: x509: certificate specifies an incompatible key usage"}
Jun 16 09:22:28 example etcd[10992]: 2025/06/16 09:22:28 WARNING: [core] [Channel #3 SubChannel #4] grpc: addrConn.createTransport failed to connect to {Addr: "[::]:2379", ServerName: "[::]:2379", }. Err: connection error: desc = "error reading server preface: remote error: tls: bad certificate"
```
This can be confirmed from the generated cert:
```shell
$ openssl x509 -in /var/lib/etcd/certs/etcd-server.pem -noout -text |grep -A2 …
```
=> Fix incompatible key usage errors for etcd v3.5

REFERENCE.md, manifests/repo.pp
The current package repository for CRIO is incorrect according to https://github.com/cri-o/packaging. The current value does not work on RedHat nodes:
```
Status code: 403 for https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.32/rpmrepodata/repomd.xml.key (IP: 18.244.214.76)
```
By moving the package base to a parameter, this would allow someone to 
* fix it should the group change it again
* choose to run another variant such as an unstable build
=> Fix crio package repository, allow data adjustment

REFERENCE.md, manifests/common.pp, manifests/init.pp
This improves support for cases where `/etc/facter` - and `facts.d` - is managed with non-standard config in the same environment - FreeBSD in our case
=> Add parameter to defer management of /etc/facter/facts.d
